import unittest

from test_baidu import TestBaiDu
from test_login_1 import TestLogin
from test_mathfunc import TestMathFunc
from HTMLTestRunner import HTMLTestRunner
if __name__ == '__main__':
    suite = unittest.TestSuite()


    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestLogin))
    # suite中也可以套suite

    # 将测试结果输出到测试报告中
    # with open('UnittestTextReport.txt', 'a') as f:
    #     runner = unittest.TextTestRunner(stream=f, verbosity=2)
    #     runner.run(suite)

    # 将测试结果输出到测试报告html中
    with open('report.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='moj',
                                description='test generated by HTMLTestRunner.',
                                verbosity=2
                                )
        # runner = BeautifulReportRunner(stream=f,
        #                                description='测试报告描述',
        #                                title='测试报告标题',
        #                                verbosity=2)
        runner.run(suite)

    # 直接将结果输出到控制台
    # runner = unittest.TextTestRunner(verbosity=2)
    # runner.run(suite)